name: e2e

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  e2e:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node: ['18', '20']
        bundler: ['vite', 'webpack']

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v2

      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build source files
        run: pnpm build

      - name: E2E dev
        working-directory: ./e2e
        run: pnpm e2e:ci-dev
        env:
          E2E_BUNDLER: ${{ matrix.bundler }}

      - name: E2E build
        working-directory: ./e2e
        run: pnpm e2e:ci-build
        env:
          E2E_BUNDLER: ${{ matrix.bundler }}

  e2e-result:
    if: ${{ always() }}
    name: e2e result
    runs-on: ubuntu-latest
    needs: [e2e]
    steps:
      - if: ${{ contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled') }}
        run: exit 1
